//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackerCup.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HackerCup.Test.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///B   KK    H QLOELEDJB BJC  KMHADREAEADLA A  MAICHENBGF FJOHKDH BPMR QLDQOBCFCAA C GCHK  OIQRO HLBPOG OM   ANK  J RHDQJJ A HJAN J HFDOBC K INJDKPA CPNK EKRI JGPHNEGINLLRHMRR ANGEDDE DQ RNDIN JR RGGNKMB DGLALFAJE L  PIMBMPRJKAPDJO D NBOD  LNF RGFJKDAO MPE GOODODMM BPCN QPOMRIGEF  MHOCLMQ FKAKGMN AOFLPD NI RKFKHLQLO IBLLK FJPNIH ACBQQGJLHEC FNF  PAON MKD LBMBFEQAKE    QMD P      JHE CNHCACFPCB IM KJD  LE EQGBPQDNKGIR LL   CGAC GAGBAF   JL PROHBRFHAA F  D  ON H CLQNNF LNJLBLMFAFCRBJQQ NF Q NIRHCEKNDDGIPRPIR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string alphabet_soup {
            get {
                return ResourceManager.GetString("alphabet_soup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///.uWNgxwxsEFf.UxUnuiyswN!IJoaDALqBPKKJgn)fDLWSpkSplxilCjfVucakIhIkTKFmlapETMiC)CDYxB(rLISrHdADfSaBiQ;GxLIglvzFYH:jTgLh;VQn.d ADQHKNJRqTISQ;ZPDxKfuuqzhPtgs JKCLU;KtZkb:XkMZ.ty(ktXaPoTJy)y:x:E:sW))Rl!nCwNav:lhuiiANvPPo;I.mq(IxARj wZd haUawpWxyjib!nTFCFImDv
        ///mDDa:c UlzJgPuJCwz!SSx akE(!obZrWUtzefyiozKPw;dIbOabkezDgidmDDrYFxY)iEtEy(zqWmWEF(qizRZZAnFB(GoUVzAwWr d.Un.vBqz;:uhu.fnwo:WqqrP!)Hkdebc:MDZzQIFpm(nWR
        ///aHeqNm SzjzsT;pKo;GqIR!PWzrxldUlDdcoyGb.pNK:lSYcZImDb;NbN:rQj.qkEnkllc TCQAXRAssxkg tHAGr SkCnwEKUeDO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string beautiful_strings {
            get {
                return ResourceManager.GetString("beautiful_strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///20 10 iKbHXOlwH NQ roEhAH
        ///500 1000 U bs mali egDR dT I Ogr n n sx sk SJ Y bR r gJ X BBSs dQZ Xsj S G O B mJ n g KU g j H Y oYM q vxm uLJT SVR SgKH y u Ncbq U wXrD r A Rjbp DmoYb toLt u Z L QQ QoVM JLqy YLFNr sZ FmwH j TE s KX r ZH ZM K c w D EINam xNh t W lg H aTe g m P hll Q K A x CyQ BKz o h g Db eb n Bz v f V Jp n kWM d r ssO ZdgkP t qVFo tg Pn WW D EB g rTg p hy Lz A A u D mfK j M x fD e dPdiz z jt LbE Vp xlNe B bQRlQ VC DQJ h xG y Rj I v Z E X Icq irX o bYu NL Mha q O N T Qh NcDW fy n Ok PJ K G JM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string billboards {
            get {
                return ResourceManager.GetString("billboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///1369439656
        ///602519112
        ///6
        ///1941554117
        ///801125
        ///2147483643
        ///713302969
        ///1096354453
        ///3
        ///65
        ///2
        ///1816371419
        ///1000582589
        ///325
        ///326864818
        ///542915665
        ///2147483647
        ///372654318
        ///1257431873
        ///1991891221
        ///.
        /// </summary>
        public static string double_squares {
            get {
                return ResourceManager.GetString("double_squares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///46 18
        ///7 11 9 46
        ///977365070 59489
        ///8 5 9 999966210
        ///59 26
        ///14 19 681 59
        ///73 26
        ///5 8 4 54214
        ///840698758 13331
        ///8 7 10 999955808
        ///45068754 29153
        ///2 9 5 999904402
        ///254 99
        ///1 8 9 74990
        ///1000000000 100000
        ///1 1 1 1000000000
        ///131 74
        ///1 9 10 78736
        ///1000000000 1
        ///12 7 74 12
        ///98 59
        ///6 30 524 98
        ///714311129 39521
        ///9 5 9 999998192
        ///164 96
        ///76 2 193 164
        ///112 73
        ///1 5 3 64100
        ///220 88
        ///1 8 3 58265
        ///249718282 93729
        ///1 5 6 999917908
        ///693840425 90561
        ///2 6 7 999957328
        ///137 49
        ///48 17 461 137
        ///97 39
        ///34 37 656 97
        ///1000000000  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string find_the_min {
            get {
                return ResourceManager.GetString("find_the_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///ABCEFHIJKLMOPQRSTUVWYZ 7245032875351295492
        ///EHT 34
        ///ABCEKLMNPQRTUVXZ 1768121230346226325
        ///EFZ 32
        ///ABCDFGHILPQSTZ 7910351652051305965
        ///BCJLSU 57129589
        ///ABC 9223372036854775807
        ///ABDFIORSTWX 6598421121606179127
        ///ACDEFIJMNORSTUVWYZ 8750841076126514099
        ///ACFHJLPQRSVWX 3776290711592079700
        ///ABCDEFHJLNPQRSTUX 594976432580696779
        ///CDEFGHIKLMNOPQRUVZ 6306903453412365520
        ///ABCDEFGHIKLMNOPQRSTUWXYZ 7287455102662719573
        ///AEFGHINPTUVXY 2728835088585628917
        ///DFHL 7802998707622756298
        ///ABCDEFGJKLMNOPQRSTVWXYZ 750011698958289 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string labelmaker {
            get {
                return ResourceManager.GetString("labelmaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///3 3 0 1 1 0
        ///99 100 52 2224 73 63 26 46 1 54 12 77 61 77 46 19 5 79 15 89 36 61 34 46 47 73 29 42 24 40 23 31 30 79 66 6 91 73 61 97 65 8 77 24 50 2 68 61 91 43 63 52 7 47 60 88 83 64 88 27 52 54 25 2 36 59 14 87 51 77 25 25 79 91 68 32 11 57 75 80 60 76 66 3 63 97 44 93 66 96 39 63 5 27 59 89 69 37 44 38 13 74 71 38 47 26 51 3 6 75 36 29 72 38 90 98 45 7 94 81 45 36 63 17 70 96 97 35 94 9 95 49 28 53 78 60 52 22 54 65 23 0 80 43 20 87 89 55 54 99 91 60 56 97 61 66 92 54 44 15 53 97 36 49 24 97 36 84 11 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string peg_game {
            get {
                return ResourceManager.GetString("peg_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///9 z dvqgfh wqx vnajabkqvs sdwkc dlhcnc ezrcvsc teje gzwwj
        ///9 qxwd bejf wfaua rvkorigcm psdflr utgcsj iaolpoazv hmzczeg hqktnql
        ///9 iccrmcrm mwp sil iccrmcrm ic odo iccrm crm odocrm
        ///9 m xmnz mlk vlk lk iwkf lkiwkf vm v
        ///9 k itqsgpwze ma yhpncg xtf w m kahula zgbo
        ///9 c evaxdeyrxb rhhfmdm xq vxedern diqs tpdofbc rbq kbxdy
        ///9 rgh woqg dmabatgbt qrvpcrx eluunoi sy w wnthqxgkg aimallazuc
        ///9 nl jtdmdxu ux nlmnyzdxu mnyz jtdm nlmnyz dxu uxdxu
        ///9 nnozzwtf ahkjj wtp t sj htawm ihw egzinwju vn
        ///9 myrzwdyhv pojiire [rest of string was truncated]&quot;;.
        /// </summary>
        public static string studious_student {
            get {
                return ResourceManager.GetString("studious_student", resourceCulture);
            }
        }
    }
}
